// REDUX ACTION TYPES
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const RESET = 'RESET';

export const USER_UPDATE = 'USER UPDATE';
export const USERNAME_UPDATE = 'USERNAME UPDATE';

export const SUPABASE_USER = "SUPABASE USER";

export const ADD_TO_STORE_INSERT = "ADD_TO_STORE_INSERT";
export const ADD_TO_STORE_PRODUCT_QUANTITY_INC = "ADD_TO_STORE_PRODUCT_QUANTITY_INC";
export const ADD_TO_STORE_PRODUCT_QUANTITY_DEC = "ADD_TO_STORE_PRODUCT_QUANTITY_DEC";
export const ADD_TO_STORE_UPDATE = "ADD_TO_STORE_UPDATE";
export const ADD_TO_STORE_DELETE = "ADD_TO_STORE_DELETE";