// REDUX ACTION TYPES
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const RESET = 'RESET';

export const USER_UPDATE = 'USER UPDATE';
export const USERNAME_UPDATE = 'USERNAME UPDATE';

export const SUPABASE_USER = "SUPABASE USER";