// REDUX ACTION TYPES
export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';
export const RESET = 'RESET';

export const USER_UPDATE = 'USER UPDATE';
export const USERNAME_UPDATE = 'USERNAME UPDATE';

export const SUPABASE_USER = "SUPABASE USER";

export const ADD_TO_CART_INSERT = "ADD_TO_CART_INSERT";
export const ADD_TO_CART_PRODUCT_QUANTITY_INC = "ADD_TO_CART_PRODUCT_QUANTITY_INC";
export const ADD_TO_CART_PRODUCT_QUANTITY_DEC = "ADD_TO_CART_PRODUCT_QUANTITY_DEC";
export const ADD_TO_CART_UPDATE = "ADD_TO_CART_UPDATE";
export const ADD_TO_CART_DELETE = "ADD_TO_CART_DELETE";


export const ADD_TO_CART_ADDRESS_CREATE = "ADD_TO_CART_ADDRESS_CREATE";
export const ADD_TO_CART_ADDRESS_UPDATE = "ADD_TO_CART_ADDRESS_UPDATE";
export const ADD_TO_CART_ADDRESS_DELETE = "ADD_TO_CART_ADDRESS_DELETE";

export const FETCH_DELIVERY_OPTIONS = 'FETCH_DELIVERY_OPTIONS';
export const UPDATE_DELIVERY_OPTION = 'UPDATE_DELIVERY_OPTION';
export const CREATE_DELIVERY_OPTION = 'CREATE_DELIVERY_OPTION';

export const UPDATE_SUBTOTAL = 'UPDATE_SUBTOTAL';
export const UPDATE_TAX = 'UPDATE_TAX';
export const UPDATE_DELIVERY_COST = 'UPDATE_DELIVERY_COST';
export const UPDATE_TOTAL_COST = 'UPDATE_TOTAL_COST';

export const FETCH_EVENT_REQUEST = 'FETCH_EVENT_REQUEST';